"""Shared defaults for visible-browser publisher downloads."""

DEFAULT_BROWSER_SPEED = "careful"
DEFAULT_PERSISTENCE_SECONDS = 3 * 24 * 60 * 60
DEFAULT_LOGIN_TIMEOUT_SECONDS = DEFAULT_PERSISTENCE_SECONDS
DEFAULT_BROKER_TTL_SECONDS = DEFAULT_PERSISTENCE_SECONDS
DEFAULT_KEEPALIVE_INTERVAL_SECONDS = 30 * 60
